<?php
/**
 * Страница "Форма редактирования раздела".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Partition bar item editing form</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/form.png' ?>" />
    </div>
    <p>The form appears after clicking the <b>"Add"</b> button on the menu partition bar list toolbar or selecting the <b>"Edit"</b> item from the context menu of the selected entry.</p>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_spinner"></span> <b>Index.</b> The section's ordinal number in the list. Used to organize sections;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Name.</b> Section name;</li>
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Belongs to.</b> If a section is a subsection, then it is necessary to indicate to whom it belongs.</li>
    </ul>

    <h3>Icon</h3>
    <p>Choose how the icon will be displayed in the section bar element by selecting the desired option in the group of flags. Each flag specifies a different display method: for example, from Font Awesome, from a URL, or as a system icon.</p>
</article>