<?php
/**
 * Страница "Форма редактирования раздела".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Partition bar item editing form</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/form.png' ?>" />
    </div>
    <p>The form appears after clicking the <b>"Add"</b> button on the menu partition bar list toolbar or selecting the <b>"Edit"</b> item from the context menu of the selected entry.</p>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><b>Index.</b> The index number of the partition in the list. Used to order partitions in the Panel;</li>
        <li><b>Name.</b> Partition name;</li>
        <li><b>Partition belongs.</b> If the partition is a subpartition, then it is necessary to indicate to whom it belongs;</li>
        <li><b>Icon.</b> Select a partition icon from Font Awesome or URL;</li>
        <li><b>Visible.</b> Show or hide partition.</li>
    </ul>
</article>