<?php
/**
 * Страница "Список разделов".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Список разделов</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/grid.png' ?>" />
    </div>
    <p>В списке отображаются все разделы Панели.</p>
    <h2>Столбцы списка</h2>
    <ul class="g-help-list">
        <li><b>Порядок.</b> Порядковый номер раздела в списке. Применяется для упорядочивания разделов в Панели;</li>
        <li><b>Название.</b> Название раздела;</li>
        <li><b>Название (текущий язык).</b> Название раздела для текущего языка;</li>
        <li><b>Значок / Изображение.</b> Значок (шрифт "Font Awesome") или изображение (URL-адрес) раздела;</li>
        <li><b>Код.</b> Уникальный код для каждого раздела. Применяется для определения идентификатора раздела;</li>
        <li><b>Роли пользователей.</b> Роли пользователей для которых будут доступны разделы;</li>
        <li><b>Модули.</b> Модули, которые будут отображаться в разделах;</li>
        <li><b>Расширения.</b> Расширения модулей, которые будут отображаться в разделах;</li>
        <li><b>Количество.</b> Количество подразделов в разделе;</li>
        <li><b>Видимость.</b> Показать или скрыть раздел.</li>
    </ul>

    <h2>Панель инструментов</h2>
    <ul class="g-help-list">
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-add.svg' ?>" /> <b>Добавить.</b> Вызывает форму для добавления раздела;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-delete.svg' ?>" /> <b>Удалить.</b> Удаляет выделенные записи разделов;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/cleanup.svg' ?>" /> <b>Очистить.</b> Удаляет все записи разделов;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-edit.svg' ?>" /> <b>Правка.</b> Вызвает форму для редактирования записи раздела;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-select.svg' ?>" /> <b>Выделить.</b> Выделяет или убирает выделение записией разделов;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/refresh.svg' ?>" /> <b>Обновить.</b> Обновляет список записей;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-profiling-off.svg' ?>" /> <b>Профилирование записи.</b> Разворачивает или сворачивает Панель навигации для отображения информации о выбранной записи раздела;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-toggle-columns-off.svg' ?>" /> <b>Показать.</b> Показывает  скрытые столбцы;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/help.svg' ?>" /> <b>Справка.</b> Вызывает окно справочной информации для текущего списка;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/search.svg' ?>" /> <b>Поиск.</b> Вызывает форму поиска записей в списке;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/filter.svg' ?>" /> <b>Фильтр.</b> Вызывает форму фильтрации записей в списке.</li>
    </ul>
</article>