<?php
/**
 * Страница "Содержание".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Partition Bar</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>The module provides functionality for adding links to GePanel Control Panel components (modules, module extensions, widgets, plugins) and organizing them by functionality into structured sections.</p>

    <h2>Contents:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('grid') ?>">List of partition bar items</a></li>
        <li><a href="<?= $url('form') ?>">Editing partition bar item</a></li>
    </ul>
</article>